=== shivam2003-dev/WT_Practical_7/P3.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="shopping">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="order" maxOccurs="unbounded">
                 <xs:complexType>
                    <xs:sequence>
                        <xs:element name="order_id" type="xs:positiveInteger"/>
                        <xs:element name="description" type="xs:string"/>
                        <xs:element name="request_date" type="xs:date"/>
                        <xs:element name="line_items" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="book">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="book_id" type="xs:positiveInteger"/>
                                                <xs:element name="book_name" type="xs:string"/>
                                                <xs:element name="genre">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="science-fiction"/>
                                                            <xs:enumeration value="mystery"/>
                                                            <xs:enumeration value="thriller"/>
                                                            <xs:enumeration value="drama"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                                <xs:element name="publish_date" type="xs:date"/>
                                                <xs:element name="authors" minOccurs="1" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="author" maxOccurs="unbounded" minOccurs="0">
                                                                <xs:complexType>
                                                                    <xs:sequence>
                                                                        <xs:element name="bio" type="xs:string" />
                                                                        <xs:element name="first_name" type="xs:string"  />
                                                                        <xs:element name="last_name" type="xs:string"  />
                                                                        <xs:element name="pen_name" minOccurs="0" type="xs:string" />
                                                                    </xs:sequence>
                                                                    <xs:attribute name="id" use="optional" type="xs:integer" />
                                                                </xs:complexType>
                                                            </xs:element>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>     
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>    
                                    <xs:element name="quantity" type="xs:byte"/>
                                    <xs:element name="price">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="1"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>                     
                    </xs:sequence>
                    </xs:complexType>
                </xs:element>    
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== shivam2003-dev/WT_Practical_7/P3.xml
<?xml version="1.0" encoding="UTF-8"?> 
<shopping  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='P3.xsd'>
        <order>
            <order_id>2019001</order_id>
            <description>This is the  description of the ordered books: The order is to be delivered to Mr. ABC</description>
            <request_date>2019-10-11</request_date>
            <line_items>
                <book>
                    <book_id>7623</book_id>
                    <book_name>Programming With C</book_name>
                    <genre>science-fiction</genre>
                    <publish_date>2011-10-10</publish_date>
                    <authors>
                        <author id="311">
                            <bio>C Language is the Mother of all languages.</bio>
                            <first_name>X</first_name>
                            <last_name>YZ</last_name>
                            <pen_name></pen_name>
                        </author>
                    </authors>
                </book>
                <quantity>10</quantity>
                <price>1000</price>
            </line_items>
        <line_items>    
            <book>
                <book_id>7624</book_id>
                <book_name>Thriller With Us</book_name>
                <genre>thriller</genre>
                <publish_date>2013-10-11</publish_date>
                <authors>
                    <author id="302">
                        <bio>Thrill- a sudden feeling of excitement and pleasure.</bio>
                        <first_name>A</first_name>
                        <last_name>BC</last_name>
                        <pen_name>abc</pen_name>
                    </author>
                    <author id="303">
                        <bio>Adventure- an unusual and exciting or daring experience.</bio>
                        <first_name>P</first_name>
                        <last_name>QR</last_name>
                        <pen_name>pqr</pen_name>
                    </author>
                </authors>    
            </book>
            <quantity>2</quantity>
            <price>10000</price>
        </line_items>
         <line_items>    
            <book>
                <book_id>9999</book_id>
                <book_name>The Daily Dramas</book_name>
                <genre>drama</genre>
                <publish_date>2019-10-19</publish_date>
                <authors>
                    <author id="301">
                        <bio>Drama- an exciting, emotional, or unexpected event or circumstance.</bio>
                        <first_name>A</first_name>
                        <last_name>SD</last_name>
                        <pen_name>asd</pen_name>
                    </author>
                    <author id="320">
                        <bio>Acting- temporarily doing the duties of another person.</bio>
                        <first_name>F</first_name>
                        <last_name>GH</last_name>
                        <pen_name>fgh</pen_name>
                    </author>
                </authors>    
            </book>
            <quantity>2</quantity>
            <price>999</price>
        </line_items>
        </order>
</shopping>
